POST localhost:8080/adopter
Content-Type: application/json

{"name": "Luis", "phoneNumber": "584-001-580", "dateAdoption": "2024-04-15"}
###

POST localhost:8080/adopter
Content-Type: application/json

{"name": "Melissa", "phoneNumber": "114-401-577", "dateAdoption": "2024-04-21", "typePet": "Cat", "namePet": "Pelusa", "breedPet": "NA"}
###

DELETE localhost:8080/api/adopter/2
###

POST localhost:8080/adopter
Content-Type: application/json

{"name": "karla", "phoneNumber": "104-401-577", "dateAdoption": "2024-04-22", "typePet": "Dog", "namePet": "Rex", "breedPet": "Callejero"}
###

PUT localhost:8080/api/adopter
Content-Type: application/json

{"idAdopter": 3,"name": "Melisa Ramirez Update", "phoneNumber": "111-000-111", "date": "2000-01-01", "pets": [{"idPet":4, "idTypePet": "Dog", "namePet": "Luna update", "breedPet": "Husky Siberiano"}] }
###

GET http://localhost:8080/api/adopter/getAllAdopters
###

GET http://localhost:8080/api/adopter/getAdopterById/6
###